### ISSUE TITLE
Issue with updating my app targated version to 31

### ISSUE THREAD

**Issue by vakhileshwar** [contentstack/contentstack-android#20]
I am using  **'com.contentstack.sdk:android:3.10.0'** in my app, and my app targetedSDKversion is 30
Its working fine

Now I am updating my app targetedSDKversion to 31 because of Content stack SDK manifest file is not compatible to sdk version 31 I unable to run/compile the app

it is throwing error says 
_android:exported needs to be explicitly specified for . Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. src/main/AndroidManifest.xml_

This is because of content stack manifest file receivers do not specified android:exported in their receivers , I did it locally in  generated Content stack sdk:android:3.10.0 manifest

Could you please help me!

**Comment by ishaileshmishra** [comment]
@vakhileshwar Thanks for raising the issue. We will look into this.

**Comment by ishaileshmishra** [comment]
Hi @vakhileshwar, 
We have resolved the compile issue on target version 31, please add the updated dependency v3.10.1.
