### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError(CSAppUtils.java line 97)

### ISSUE THREAD

**Issue by vakhileshwar** [contentstack/contentstack-android#22]
We integrated CS in my Android app, and release the app to play store
We saw crashes in firebase in class  CSAppUtils.

Here is log

Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 80 byte allocation with 13200 free bytes and 12KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.

com.contentstack.sdk.utilities.CSAppUtils.getJsonFromCacheFile (CSAppUtils.java:97)
com.contentstack.sdk.utilities.CSAppUtils.getResponseTimeFromCacheFile (CSAppUtils.java:45)
com.contentstack.sdk.Query.execQuery (Query.java:1781)
com.contentstack.sdk.Query.find (Query.java:1553)
com.modere.data.model.Content.continueGetContent (Content.kt:401)
com.modere.data.model.Content.access$continueGetContent (Content.kt:21)
com.modere.data.model.Content$getContent$1.onCompletion (Content.kt:355)
com.contentstack.sdk.QueryResultsCallBack.onRequestFinish (QueryResultsCallBack.java:12)
com.contentstack.sdk.Query.setCacheModel (Query.java:1934)
com.contentstack.sdk.Query.execQuery (Query.java:1790)
com.contentstack.sdk.Query.find (Query.java:1553)
myAppCalss.getContent (Content.kt:333)

Could you please help us to fix the issue! we have 62 crashes with this issue in last couple of days!

**Comment by vakhileshwar** [comment]
I do have same memory issue at
 CSConnectionRequest.java line 306
com.contentstack.sdk.CSConnectionRequest.createFileIntoCacheDir

**Comment by ishaileshmishra** [comment]
Thanks for raising the issue @vakhileshwar, We will look into it.

**Comment by ishaileshmishra** [comment]
@vakhileshwar, While we are investigating the cause of the crash. here is a quick solution that might help, you can try adding the below entities to your manifest file 

```
android:hardwareAccelerated="false", 
android:largeHeap="true" 
```

It will work for some environments

```
<application
    android:allowBackup="true"
    android:hardwareAccelerated="false"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:largeHeap="true"
    android:supportsRtl="true"
    android:theme="@style/AppTheme">
```

**Comment by vakhileshwar** [comment]
We need hardwareAccelerated to be true for one of my other functionalities
and Yes largeHeap may help, but I google document says it is risky to use, as app may be removed from background in lower memory situations.

**Comment by vakhileshwar** [comment]
@ishaileshmishra We are using 'com.contentstack.sdk:android:3.10.1'

**Comment by vakhileshwar** [comment]
@ishaileshmishra Any updates on the issue?

**Comment by vakhileshwar** [comment]
Do we have any fix for the crash, please let us know!
