### ISSUE TITLE
Security Issue : Implicit PendingIntent detected in ContentStack Android SDK 3.10.1

### ISSUE THREAD

**Issue by NithinAY** [contentstack/contentstack-android#23]
When we tried to publish our first release on the Play store, unfortunately, we got a security error pointing to the ContentStack Android SDK. We investigated more on this and found the implementation of the `Contentstack::clearCache(Context)` method has a PendingIntent which is causing this issue. 
The Google Guidelines for the same can be found here: https://support.google.com/faqs/answer/10437428

**Comment by ishaileshmishra** [comment]
Thanks for writing us @NithinAY, We are looking into it.

**Comment by NithinAY** [comment]
@ishaileshmishra Raised a PR https://github.com/contentstack/contentstack-android/pull/24 with the fix. Hope it helps. Thank you.

**Comment by ishaileshmishra** [comment]
Hi @NithinAY, Please update the dependency to [v3.10.2](https://search.maven.org/artifact/com.contentstack.sdk/android/3.10.2/aar).

closing the issue, feel free to open it again if it does not solve the issue
