### ISSUE TITLE
Null Pointer Exception in Android SDK when accessing "publish_details" array

### ISSUE THREAD

**Issue by philculver** [contentstack/contentstack-android#30]
Description:

While using the ContentStack Android SDK version 3.10.0, we encountered a null pointer exception when attempting to access the "publish_details" array from a JSON object. This issue occurs when the JSON object does not contain the "publish_details" array or when the array is null. It leads to a warning in the app when trying to call the length() method on a null object.

Steps to reproduce:

1. Integrate ContentStack Android SDK into an Android project.
2. Fetch a JSON object that does not contain the "publish_details" array or contains a null value for it.
3. Attempt to access and iterate through the "publish_details" array using the provided SDK code.

Expected behavior:

The SDK should handle cases where the "publish_details" array is not present or is null without throwing a null pointer exception.

Actual behavior:

A null pointer exception is thrown when trying to call the length() method on a null object, leading to warnings in the app.

<img width="916" alt="Screen Shot 2023-03-16 at 4 30 56 PM" src="https://user-images.githubusercontent.com/77158601/233699224-911654b9-7916-475a-9452-1e2e9e255dc2.png">

Proposed solution:

Add a null check before iterating through the publishArray. Here's a suggested modification to the SDK code:

```JSONArray publishArray = jsonObject.optJSONArray("publish_details");
if (publishArray != null) {
    for (int i = 0; i < publishArray.length(); i++) {
        JSONObject publishObject = publishArray.optJSONObject(i);
        Iterator<String> iterator = publishObject.keys();
        HashMap<String, Object> hashMap = new HashMap<>();
        while (iterator.hasNext()) {
            String key = iterator.next();
            hashMap.put(key, publishObject.opt(key));
        }
    }
} else {
    Log.e("ContentStack", "publish_details array not found or is null");
}

**Comment by ishaileshmishra** [comment]
Thank you for writing to us, @philculver. We are working on it and will update you soon with the updated dependency
