### ISSUE TITLE
Is not able to change the region if we use the method stack for getting the object Stack

### ISSUE THREAD

**Issue by inmaculadaalcon** [contentstack/contentstack-android#35]
Hi, I faced this problem this morning.
When I try to change the region to EU after set in the config object, the region by default is still being US. 
I saw the code inside the Contentstack.java and the problem is the line 73, because any config I set in the method 
public static Stack stack(@NotNull Context context, @NotNull String apiKey, @NotNull String deliveryToken, @NotNull String environment, @NotNull Config config) throws Exception {
     is replaced by the line 73 creating another new config object and that's wrong.

 ```java
public static Stack stack(@NotNull Context context, @NotNull String apiKey, @NotNull String deliveryToken, @NotNull 
                                                                               String environment, @NotNull Config config) throws Exception {
     if (!TextUtils.isEmpty(apiKey) || !TextUtils.isEmpty(deliveryToken) || !TextUtils.isEmpty(environment)) {
            config = new Config();  //This is the line 73
            config.setEnvironment(environment);
            return initializeStack(context, apiKey, deliveryToken, config);
     } else {
            throw new Exception(SDKConstant.EMPTY_CREDENTIALS_NOT_ALLOWED);
     }
}
```

     The version I am using is the last one, 3.12.0

**Comment by ishaileshmishra** [comment]
@inmaculadaalcon Please update the dependency to 3.12.1

```
<!-- https://mvnrepository.com/artifact/com.contentstack.sdk/android -->
<dependency>
    <groupId>com.contentstack.sdk</groupId>
    <artifactId>android</artifactId>
    <version>3.12.1</version>
</dependency>
```
