### ISSUE TITLE
For Setting the Branch for a Region

### ISSUE THREAD

**Issue by jonghobaek-costco** [contentstack/contentstack-android#37]
The Android section of the Contentstack documentation mentions the part ["For Setting the Branch for a Region"](https://www.contentstack.com/docs/developers/contentstack-regions/selecting-region-in-sdks#android). It suggests that if you want to use a specific branch during the SDK initialization process, you should use the `Config::setBranch()` method.

However, I cannot find the `Config::setBranch()` method in the Contentstack SDK for Android. Could you please provide guidance on how to utilize a specific branch during SDK initialization? 

The following sample code is extracted from the "For Setting the Branch for a Region" section of the Contentstack documentation:
```
Config config = Config();
config.setRegion(ContentstackRegion.<<add_your_region>>);
config.setBranch("branch");
Stack stack = Contentstack.stack("api_key", "delivery_token", "environment_name", config);
```

Please provide me with the correct method or approach to set a specific branch during SDK initialization in the Contentstack SDK for Android.

**Comment by ishaileshmishra** [comment]
Hello @jonghobaek-costco , thanks for raising the issue. we have acknowledged the issue and have already implemented the necessary fixes. We are planning to provide an updated build by the end of next week.
