### ISSUE TITLE
v3.12.1 SDK couldn't be downloaded

### ISSUE THREAD

**Issue by jonghobaek-costco** [contentstack/contentstack-android#41]
Hi, Contentstack team,
The [v3.12.1 SDK](https://github.com/contentstack/contentstack-android/releases/tag/v3.12.1) couldn't be downloaded.
This issue can be reproduced on your [contentstack-android-ecommerce-app](https://github.com/contentstack/contentstack-android-ecommerce-app) sample app.
Please check this download issue.

**Comment by ishaileshmishra** [comment]
Thanks for raising issue @jonghobaek-costco, we are looking into this

**Comment by ishaileshmishra** [comment]
The downloading issue has been resolved. Please implement latest versions of the dependency.  closing the issue, feel free to re-open it in case issue persists
